USE [Timetable]
GO
/****** Object:  Table [dbo].[ACADEMIC_PERIOD]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACADEMIC_PERIOD](
	[PYear] [smallint] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[StartDate] [datetime] NOT NULL,
 CONSTRAINT [PK_ACADEMIC_PERIOD] PRIMARY KEY CLUSTERED 
(
	[PYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACADEMIC_STAFF]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACADEMIC_STAFF](
	[ID] [smallint] NOT NULL,
	[DID] [smallint] NOT NULL,
	[JobTitle] [nchar](10) NULL,
	[Salary] [smallmoney] NULL,
	[StartDate] [date] NOT NULL,
	[WorkHours] [smallint] NULL,
	[username] [nchar](10) NOT NULL,
	[UID] [smallint] NOT NULL,
	[FName] [nchar](20) NOT NULL,
	[MName] [nchar](10) NULL,
	[LName] [nchar](10) NOT NULL,
	[PostCode] [nchar](10) NOT NULL,
	[AdNumber] [tinyint] NOT NULL,
	[Street] [nchar](100) NOT NULL,
	[personalIDNo] [smallint] NOT NULL,
	[MPhone] [int] NULL,
	[Gender] [bit] NULL,
	[DOB] [date] NOT NULL,
	[Age] [tinyint] NOT NULL,
	[uniEmail] [nchar](320) NOT NULL,
 CONSTRAINT [PK_ACADEMIC_STAFF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[username] [nchar](10) NOT NULL,
	[password] [nchar](10) NOT NULL,
 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN_OFFICE_ACADEMICS]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN_OFFICE_ACADEMICS](
	[ID] [smallint] NOT NULL,
	[JobTitle] [nchar](10) NULL,
	[Salary] [smallmoney] NULL,
	[StartDate] [date] NOT NULL,
	[WorkHours] [int] NULL,
	[username] [nchar](10) NOT NULL,
	[UID] [smallint] NOT NULL,
	[FName] [nchar](10) NOT NULL,
	[MName] [nchar](10) NULL,
	[LName] [nchar](10) NOT NULL,
	[PostCode] [nchar](10) NOT NULL,
	[AdNumber] [tinyint] NOT NULL,
	[Street] [nchar](100) NOT NULL,
	[personalIDNo] [int] NOT NULL,
	[MPhone] [int] NULL,
	[Gender] [bit] NULL,
	[Age] [tinyint] NOT NULL,
	[uniEmail] [nchar](320) NOT NULL,
 CONSTRAINT [PK_ADMIN_OFFICE_ACADEMICS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ATTENDANCE]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATTENDANCE](
	[SID] [smallint] NOT NULL,
	[LectureKey] [tinyint] NOT NULL,
	[Attendance] [bit] NOT NULL,
	[PYear] [smallint] NOT NULL,
	[PID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[Date] [date] NOT NULL,
 CONSTRAINT [PK_ATTENDANCE] PRIMARY KEY CLUSTERED 
(
	[SID] ASC,
	[LectureKey] ASC,
	[PYear] ASC,
	[PID] ASC,
	[MCode] ASC,
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[DID] [smallint] NOT NULL,
	[AID] [smallint] NULL,
	[SID] [smallint] NOT NULL,
	[DName] [nchar](10) NOT NULL,
	[NumOfProgrammes] [smallint] NULL,
	[NumOfStudents] [int] NULL,
 CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED 
(
	[DID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LECTURE]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LECTURE](
	[PYear] [smallint] NOT NULL,
	[PID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[Date] [date] NOT NULL,
	[LectureKey] [tinyint] NOT NULL,
	[SStart] [datetime] NULL,
	[SEnd] [datetime] NULL,
	[AID] [smallint] NULL,
	[Location] [nchar](10) NULL,
 CONSTRAINT [PK_LECTURE_1] PRIMARY KEY CLUSTERED 
(
	[PYear] ASC,
	[PID] ASC,
	[MCode] ASC,
	[Date] ASC,
	[LectureKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_LECTURE] UNIQUE NONCLUSTERED 
(
	[PYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODULE_PER_YEAR]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODULE_PER_YEAR](
	[PYear] [smallint] NOT NULL,
	[PID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[MSemester] [tinyint] NULL,
 CONSTRAINT [PK_MODULE_PER_YEAR] PRIMARY KEY CLUSTERED 
(
	[PYear] ASC,
	[PID] ASC,
	[MCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODULES]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODULES](
	[DID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[MName] [nchar](100) NOT NULL,
 CONSTRAINT [PK_MODULES] PRIMARY KEY CLUSTERED 
(
	[MCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROGRAMMES]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROGRAMMES](
	[PID] [smallint] NOT NULL,
	[SID] [smallint] NOT NULL,
	[DID] [smallint] NOT NULL,
	[PName] [nchar](10) NOT NULL,
 CONSTRAINT [PK_PROGRAMMES] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECTOR]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECTOR](
	[ID] [smallint] NOT NULL,
	[JobTitle] [nchar](10) NULL,
	[Salary] [smallint] NULL,
	[StartDate] [date] NOT NULL,
	[WorkHours] [smallint] NULL,
	[username] [nchar](10) NOT NULL,
	[UID] [smallint] NOT NULL,
	[FName] [nchar](10) NOT NULL,
	[MName] [nchar](10) NULL,
	[LName] [nchar](10) NOT NULL,
	[PostCode] [nvarchar](10) NOT NULL,
	[AdNumber] [tinyint] NOT NULL,
	[Street] [nchar](20) NOT NULL,
	[PersonalIDNo] [smallint] NOT NULL,
	[MPhone] [smallint] NULL,
	[Gender] [bit] NULL,
	[DOB] [date] NOT NULL,
	[Age] [tinyint] NOT NULL,
	[uniEmail] [nvarchar](320) NOT NULL,
 CONSTRAINT [PK_RECTOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHOOL]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHOOL](
	[SID] [smallint] NOT NULL,
	[UID] [smallint] NOT NULL,
	[AID] [smallint] NULL,
	[SName] [nvarchar](20) NOT NULL,
	[NumOfProg] [smallint] NOT NULL,
	[NumOfDepartments] [smallint] NOT NULL,
	[NumOfAcademics] [smallint] NOT NULL,
 CONSTRAINT [PK_SCHOOL] PRIMARY KEY CLUSTERED 
(
	[SID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SESSION]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SESSION](
	[PYear] [smallint] NOT NULL,
	[PID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[SStart] [datetime] NOT NULL,
	[SEnd] [datetime] NOT NULL,
	[Day] [nchar](10) NOT NULL,
	[AID] [smallint] NULL,
	[Location] [nchar](10) NOT NULL,
	[TypeOfSession] [nchar](10) NULL,
 CONSTRAINT [PK_SESSION_1] PRIMARY KEY CLUSTERED 
(
	[PYear] ASC,
	[PID] ASC,
	[MCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENT]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENT](
	[ID] [smallint] NOT NULL,
	[LibraryCardNo] [smallint] NOT NULL,
	[AttendanceStatus] [nchar](5) NULL,
	[username] [nchar](10) NOT NULL,
	[UID] [smallint] NOT NULL,
	[FName] [nchar](20) NOT NULL,
	[MName] [nchar](10) NULL,
	[LName] [nchar](10) NOT NULL,
	[PostCode] [nchar](10) NOT NULL,
	[AdNumber] [tinyint] NOT NULL,
	[Street] [nchar](100) NOT NULL,
	[PersonalIDNo] [smallint] NOT NULL,
	[MPhone] [int] NULL,
	[Gender] [bit] NULL,
	[DOB] [date] NOT NULL,
	[Age] [tinyint] NOT NULL,
	[uniEmail] [nchar](320) NOT NULL,
 CONSTRAINT [PK_STUDENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS](
	[ID] [smallint] NOT NULL,
	[JobTitle] [nchar](10) NULL,
	[Salary] [smallmoney] NULL,
	[StartDate] [date] NOT NULL,
	[WorkHours] [int] NULL,
	[username] [nchar](10) NOT NULL,
	[UID] [smallint] NOT NULL,
	[FName] [nchar](10) NOT NULL,
	[MName] [nchar](10) NULL,
	[LName] [nchar](10) NOT NULL,
	[PostCode] [nchar](10) NOT NULL,
	[AdNumber] [tinyint] NOT NULL,
	[Street] [nchar](100) NOT NULL,
	[personalIDNo] [int] NOT NULL,
	[MPhone] [int] NULL,
	[Gender] [bit] NULL,
	[DOB] [date] NOT NULL,
	[Age] [tinyint] NOT NULL,
	[uniEmail] [nchar](320) NOT NULL,
 CONSTRAINT [PK_STUDENT_SUPPORT_OFFICE_ACADEMICS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TEACH]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TEACH](
	[AID] [smallint] NOT NULL,
	[Grades] [tinyint] NULL,
	[PYear] [smallint] NOT NULL,
	[PID] [smallint] NOT NULL,
	[MCode] [nchar](10) NOT NULL,
	[Date] [date] NOT NULL,
	[LectureKey] [tinyint] NOT NULL,
 CONSTRAINT [PK_TEACH_1] PRIMARY KEY CLUSTERED 
(
	[AID] ASC,
	[PYear] ASC,
	[PID] ASC,
	[MCode] ASC,
	[Date] ASC,
	[LectureKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_TEACH] UNIQUE NONCLUSTERED 
(
	[AID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UNIVERSITY]    Script Date: 07/01/2020 5:19:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UNIVERSITY](
	[UID] [smallint] NOT NULL,
	[AID] [smallint] NULL,
	[UName] [nchar](10) NOT NULL,
	[NumOfSchools] [smallint] NOT NULL,
	[NumOfDepartments] [smallint] NOT NULL,
	[NumOfProgrammes] [smallint] NOT NULL,
	[NumOfStudents] [int] NOT NULL,
 CONSTRAINT [PK_UNIVERSITY] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF]  WITH CHECK ADD  CONSTRAINT [FK_ACADEMIC_STAFF_ACCOUNT] FOREIGN KEY([username])
REFERENCES [dbo].[ACCOUNT] ([username])
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF] CHECK CONSTRAINT [FK_ACADEMIC_STAFF_ACCOUNT]
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF]  WITH CHECK ADD  CONSTRAINT [FK_ACADEMIC_STAFF_DEPARTMENT] FOREIGN KEY([DID])
REFERENCES [dbo].[DEPARTMENT] ([DID])
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF] CHECK CONSTRAINT [FK_ACADEMIC_STAFF_DEPARTMENT]
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF]  WITH CHECK ADD  CONSTRAINT [FK_ACADEMIC_STAFF_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[ACADEMIC_STAFF] CHECK CONSTRAINT [FK_ACADEMIC_STAFF_UNIVERSITY]
GO
ALTER TABLE [dbo].[ADMIN_OFFICE_ACADEMICS]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_OFFICE_ACADEMICS_ACCOUNT] FOREIGN KEY([username])
REFERENCES [dbo].[ACCOUNT] ([username])
GO
ALTER TABLE [dbo].[ADMIN_OFFICE_ACADEMICS] CHECK CONSTRAINT [FK_ADMIN_OFFICE_ACADEMICS_ACCOUNT]
GO
ALTER TABLE [dbo].[ADMIN_OFFICE_ACADEMICS]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_OFFICE_ACADEMICS_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[ADMIN_OFFICE_ACADEMICS] CHECK CONSTRAINT [FK_ADMIN_OFFICE_ACADEMICS_UNIVERSITY]
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDANCE_LECTURE] FOREIGN KEY([PYear], [PID], [MCode], [Date], [LectureKey])
REFERENCES [dbo].[LECTURE] ([PYear], [PID], [MCode], [Date], [LectureKey])
GO
ALTER TABLE [dbo].[ATTENDANCE] CHECK CONSTRAINT [FK_ATTENDANCE_LECTURE]
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDANCE_LECTURE1] FOREIGN KEY([PYear], [PID], [MCode], [Date], [LectureKey])
REFERENCES [dbo].[LECTURE] ([PYear], [PID], [MCode], [Date], [LectureKey])
GO
ALTER TABLE [dbo].[ATTENDANCE] CHECK CONSTRAINT [FK_ATTENDANCE_LECTURE1]
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDANCE_SCHOOL] FOREIGN KEY([SID])
REFERENCES [dbo].[SCHOOL] ([SID])
GO
ALTER TABLE [dbo].[ATTENDANCE] CHECK CONSTRAINT [FK_ATTENDANCE_SCHOOL]
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDANCE_STUDENT] FOREIGN KEY([SID])
REFERENCES [dbo].[STUDENT] ([ID])
GO
ALTER TABLE [dbo].[ATTENDANCE] CHECK CONSTRAINT [FK_ATTENDANCE_STUDENT]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_RECTOR] FOREIGN KEY([AID])
REFERENCES [dbo].[RECTOR] ([ID])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_RECTOR]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_SCHOOL] FOREIGN KEY([SID])
REFERENCES [dbo].[SCHOOL] ([SID])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_SCHOOL]
GO
ALTER TABLE [dbo].[LECTURE]  WITH CHECK ADD  CONSTRAINT [FK_LECTURE_SESSION] FOREIGN KEY([PYear], [PID], [MCode])
REFERENCES [dbo].[SESSION] ([PYear], [PID], [MCode])
GO
ALTER TABLE [dbo].[LECTURE] CHECK CONSTRAINT [FK_LECTURE_SESSION]
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR]  WITH CHECK ADD  CONSTRAINT [FK_MODULE_PER_YEAR_ACADEMIC_PERIOD] FOREIGN KEY([PYear])
REFERENCES [dbo].[ACADEMIC_PERIOD] ([PYear])
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR] CHECK CONSTRAINT [FK_MODULE_PER_YEAR_ACADEMIC_PERIOD]
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR]  WITH CHECK ADD  CONSTRAINT [FK_MODULE_PER_YEAR_MODULES] FOREIGN KEY([MCode])
REFERENCES [dbo].[MODULES] ([MCode])
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR] CHECK CONSTRAINT [FK_MODULE_PER_YEAR_MODULES]
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR]  WITH CHECK ADD  CONSTRAINT [FK_MODULE_PER_YEAR_PROGRAMMES] FOREIGN KEY([PID])
REFERENCES [dbo].[PROGRAMMES] ([PID])
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR] CHECK CONSTRAINT [FK_MODULE_PER_YEAR_PROGRAMMES]
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR]  WITH CHECK ADD  CONSTRAINT [FK_MODULE_PER_YEAR_SESSION] FOREIGN KEY([PYear], [PID], [MCode])
REFERENCES [dbo].[SESSION] ([PYear], [PID], [MCode])
GO
ALTER TABLE [dbo].[MODULE_PER_YEAR] CHECK CONSTRAINT [FK_MODULE_PER_YEAR_SESSION]
GO
ALTER TABLE [dbo].[MODULES]  WITH CHECK ADD  CONSTRAINT [FK_MODULES_DEPARTMENT] FOREIGN KEY([DID])
REFERENCES [dbo].[DEPARTMENT] ([DID])
GO
ALTER TABLE [dbo].[MODULES] CHECK CONSTRAINT [FK_MODULES_DEPARTMENT]
GO
ALTER TABLE [dbo].[PROGRAMMES]  WITH CHECK ADD  CONSTRAINT [FK_PROGRAMMES_DEPARTMENT] FOREIGN KEY([DID])
REFERENCES [dbo].[DEPARTMENT] ([DID])
GO
ALTER TABLE [dbo].[PROGRAMMES] CHECK CONSTRAINT [FK_PROGRAMMES_DEPARTMENT]
GO
ALTER TABLE [dbo].[PROGRAMMES]  WITH CHECK ADD  CONSTRAINT [FK_PROGRAMMES_SCHOOL] FOREIGN KEY([SID])
REFERENCES [dbo].[SCHOOL] ([SID])
GO
ALTER TABLE [dbo].[PROGRAMMES] CHECK CONSTRAINT [FK_PROGRAMMES_SCHOOL]
GO
ALTER TABLE [dbo].[RECTOR]  WITH CHECK ADD  CONSTRAINT [FK_RECTOR_ACCOUNT] FOREIGN KEY([username])
REFERENCES [dbo].[ACCOUNT] ([username])
GO
ALTER TABLE [dbo].[RECTOR] CHECK CONSTRAINT [FK_RECTOR_ACCOUNT]
GO
ALTER TABLE [dbo].[RECTOR]  WITH CHECK ADD  CONSTRAINT [FK_RECTOR_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[RECTOR] CHECK CONSTRAINT [FK_RECTOR_UNIVERSITY]
GO
ALTER TABLE [dbo].[SCHOOL]  WITH CHECK ADD  CONSTRAINT [FK_SCHOOL_RECTOR] FOREIGN KEY([AID])
REFERENCES [dbo].[RECTOR] ([ID])
GO
ALTER TABLE [dbo].[SCHOOL] CHECK CONSTRAINT [FK_SCHOOL_RECTOR]
GO
ALTER TABLE [dbo].[SCHOOL]  WITH CHECK ADD  CONSTRAINT [FK_SCHOOL_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[SCHOOL] CHECK CONSTRAINT [FK_SCHOOL_UNIVERSITY]
GO
ALTER TABLE [dbo].[STUDENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_ACCOUNT] FOREIGN KEY([username])
REFERENCES [dbo].[ACCOUNT] ([username])
GO
ALTER TABLE [dbo].[STUDENT] CHECK CONSTRAINT [FK_STUDENT_ACCOUNT]
GO
ALTER TABLE [dbo].[STUDENT]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[STUDENT] CHECK CONSTRAINT [FK_STUDENT_UNIVERSITY]
GO
ALTER TABLE [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_SUPPORT_OFFICE_ACADEMICS_ACCOUNT] FOREIGN KEY([username])
REFERENCES [dbo].[ACCOUNT] ([username])
GO
ALTER TABLE [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS] CHECK CONSTRAINT [FK_STUDENT_SUPPORT_OFFICE_ACADEMICS_ACCOUNT]
GO
ALTER TABLE [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS]  WITH CHECK ADD  CONSTRAINT [FK_STUDENT_SUPPORT_OFFICE_ACADEMICS_UNIVERSITY] FOREIGN KEY([UID])
REFERENCES [dbo].[UNIVERSITY] ([UID])
GO
ALTER TABLE [dbo].[STUDENT_SUPPORT_OFFICE_ACADEMICS] CHECK CONSTRAINT [FK_STUDENT_SUPPORT_OFFICE_ACADEMICS_UNIVERSITY]
GO
ALTER TABLE [dbo].[TEACH]  WITH CHECK ADD  CONSTRAINT [FK_TEACH_ACADEMIC_STAFF] FOREIGN KEY([AID])
REFERENCES [dbo].[ACADEMIC_STAFF] ([ID])
GO
ALTER TABLE [dbo].[TEACH] CHECK CONSTRAINT [FK_TEACH_ACADEMIC_STAFF]
GO
ALTER TABLE [dbo].[TEACH]  WITH CHECK ADD  CONSTRAINT [FK_TEACH_LECTURE] FOREIGN KEY([PYear], [PID], [MCode], [Date], [LectureKey])
REFERENCES [dbo].[LECTURE] ([PYear], [PID], [MCode], [Date], [LectureKey])
GO
ALTER TABLE [dbo].[TEACH] CHECK CONSTRAINT [FK_TEACH_LECTURE]
GO
ALTER TABLE [dbo].[UNIVERSITY]  WITH CHECK ADD  CONSTRAINT [FK_UNIVERSITY_RECTOR] FOREIGN KEY([AID])
REFERENCES [dbo].[RECTOR] ([ID])
GO
ALTER TABLE [dbo].[UNIVERSITY] CHECK CONSTRAINT [FK_UNIVERSITY_RECTOR]
GO
